//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebHome.Models.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class NamingItem2023 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NamingItem2023() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebHome.Models.Resources.NamingItem2023", typeof(NamingItem2023).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 摯愛運動，&lt;br/&gt;&lt;span class=&quot;multicolor-text-underline&quot;&gt;快樂始於Beyond&lt;/span&gt;.
        /// </summary>
        public static string AboutUsBannerSlogn {
            get {
                return ResourceManager.GetString("AboutUsBannerSlogn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 在歡愉的時光中運動，&lt;br class=&quot;hidden-sm-up&quot;&gt;為您締造與眾不同的體驗.
        /// </summary>
        public static string AboutUsBannerSlognDesc {
            get {
                return ResourceManager.GetString("AboutUsBannerSlognDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 我們相信.
        /// </summary>
        public static string AboutUsBelieve {
            get {
                return ResourceManager.GetString("AboutUsBelieve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 「若能幫助您成功的改變生活、邁向健康，自然而然可透過運動創造屬於您的人本價值及生活品質。」.
        /// </summary>
        public static string AboutUsBelieveDesc {
            get {
                return ResourceManager.GetString("AboutUsBelieveDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 品牌信念.
        /// </summary>
        public static string AboutUsBrandSlogon {
            get {
                return ResourceManager.GetString("AboutUsBrandSlogon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 對 Beyond 來說，&lt;br class=&quot;hidden-sm-up&quot;/&gt;運動是一件認真的事情.
        /// </summary>
        public static string AboutUsBrandSlogonDesc {
            get {
                return ResourceManager.GetString("AboutUsBrandSlogonDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beyond自2014年始於台北小巨蛋，至今陸續擴展至信義安和、忠孝和東門等四家分店，以超過50位專業團隊成員擁有完整組織架構，為您提供個人客製化訓練、營養諮詢、運動按摩恢復、運動傷害防護、企業團隊健康策略、專業運動教育培訓以及企業健康顧問等多元服務，並為全台最大的運動客製化訓練中心。.
        /// </summary>
        public static string AboutUsCompanyDesc1 {
            get {
                return ResourceManager.GetString("AboutUsCompanyDesc1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 我們以熱情和專業之心，為您打造獨一無二的運動體驗。無論您的目標是什麼，我們相信每個時刻都應該充滿動力與樂趣。除了定期舉辦精彩的Game Day和團隊活動，還提供移地訓練和帶領偏鄉朋友一起享受運動的機會。因為對我們來說，運動不僅是認真的事情，更是在歡愉的時光中創造價值的機會。.
        /// </summary>
        public static string AboutUsCompanyDesc2 {
            get {
                return ResourceManager.GetString("AboutUsCompanyDesc2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 預約60分鐘&lt;br class=&quot;hidden-lg-up&quot;/&gt;&lt;span class=&quot;mark-text-underline&quot; padding-width=&quot;0.1&quot; bottom-width=&quot;0.1&quot;&gt;免費體驗&lt;/span&gt;.
        /// </summary>
        public static string BookNowBannerSlogn {
            get {
                return ResourceManager.GetString("BookNowBannerSlogn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 專業1對1私人教練 立即免費預約.
        /// </summary>
        public static string BookNowBannerSlognDesc {
            get {
                return ResourceManager.GetString("BookNowBannerSlognDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 好，我了解。.
        /// </summary>
        public static string BookNowFormAgree {
            get {
                return ResourceManager.GetString("BookNowFormAgree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 如何稱呼您？ (姓名).
        /// </summary>
        public static string BookNowFormColumn1 {
            get {
                return ResourceManager.GetString("BookNowFormColumn1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 您的性別.
        /// </summary>
        public static string BookNowFormColumn2 {
            get {
                return ResourceManager.GetString("BookNowFormColumn2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 您的電子郵件.
        /// </summary>
        public static string BookNowFormColumn3 {
            get {
                return ResourceManager.GetString("BookNowFormColumn3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 聯絡人電話.
        /// </summary>
        public static string BookNowFormColumn4 {
            get {
                return ResourceManager.GetString("BookNowFormColumn4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 您希望 Beyond Fitness 幫您解決什麼問題？（可以複選）.
        /// </summary>
        public static string BookNowFormColumn5 {
            get {
                return ResourceManager.GetString("BookNowFormColumn5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 飲食管理(需要營養師協助).
        /// </summary>
        public static string BookNowFormColumn5Option1 {
            get {
                return ResourceManager.GetString("BookNowFormColumn5Option1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 健康提升(體力/精神/改善痠痛).
        /// </summary>
        public static string BookNowFormColumn5Option2 {
            get {
                return ResourceManager.GetString("BookNowFormColumn5Option2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 增肌(體態雕塑).
        /// </summary>
        public static string BookNowFormColumn5Option3 {
            get {
                return ResourceManager.GetString("BookNowFormColumn5Option3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 減肥(減脂).
        /// </summary>
        public static string BookNowFormColumn5Option4 {
            get {
                return ResourceManager.GetString("BookNowFormColumn5Option4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 孕婦產前 / 產後運動.
        /// </summary>
        public static string BookNowFormColumn5Option5 {
            get {
                return ResourceManager.GetString("BookNowFormColumn5Option5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 矯正訓練及復健訓練.
        /// </summary>
        public static string BookNowFormColumn5Option6 {
            get {
                return ResourceManager.GetString("BookNowFormColumn5Option6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 專項運動表現提升(個人突破).
        /// </summary>
        public static string BookNowFormColumn5Option7 {
            get {
                return ResourceManager.GetString("BookNowFormColumn5Option7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 培養運動習慣(教練協助).
        /// </summary>
        public static string BookNowFormColumn5Option8 {
            get {
                return ResourceManager.GetString("BookNowFormColumn5Option8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 您方便聯絡的時間？（可以複選）.
        /// </summary>
        public static string BookNowFormColumn6 {
            get {
                return ResourceManager.GetString("BookNowFormColumn6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 上午十點到十二點.
        /// </summary>
        public static string BookNowFormColumn6Option1 {
            get {
                return ResourceManager.GetString("BookNowFormColumn6Option1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 中午十二點至下午一點.
        /// </summary>
        public static string BookNowFormColumn6Option2 {
            get {
                return ResourceManager.GetString("BookNowFormColumn6Option2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 下午一點到六點.
        /// </summary>
        public static string BookNowFormColumn6Option3 {
            get {
                return ResourceManager.GetString("BookNowFormColumn6Option3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 晚間六點到九點.
        /// </summary>
        public static string BookNowFormColumn6Option4 {
            get {
                return ResourceManager.GetString("BookNowFormColumn6Option4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 您想要預約的門市地點為何？.
        /// </summary>
        public static string BookNowFormColumn7 {
            get {
                return ResourceManager.GetString("BookNowFormColumn7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請選擇.
        /// </summary>
        public static string BookNowFormColumn7Option0 {
            get {
                return ResourceManager.GetString("BookNowFormColumn7Option0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 南京店 02-2715.2733（捷運小巨蛋 1 號出口）.
        /// </summary>
        public static string BookNowFormColumn7Option1 {
            get {
                return ResourceManager.GetString("BookNowFormColumn7Option1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 信義安和店 02-2720.0530（捷運信義安和站 2A 號出口）.
        /// </summary>
        public static string BookNowFormColumn7Option2 {
            get {
                return ResourceManager.GetString("BookNowFormColumn7Option2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 忠孝店 02-2776.9932（捷運忠孝復興站 3 號＊地下街14號出口）.
        /// </summary>
        public static string BookNowFormColumn7Option3 {
            get {
                return ResourceManager.GetString("BookNowFormColumn7Option3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 東門店 02-2396.0776（捷運東門站 3 號出口）.
        /// </summary>
        public static string BookNowFormColumn7Option4 {
            get {
                return ResourceManager.GetString("BookNowFormColumn7Option4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 您有什麼疑問與其他需求呢？.
        /// </summary>
        public static string BookNowFormColumn8 {
            get {
                return ResourceManager.GetString("BookNowFormColumn8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 此問題非必填，若沒有請留空送出即可，謝謝您。.
        /// </summary>
        public static string BookNowFormColumn8Desc {
            get {
                return ResourceManager.GetString("BookNowFormColumn8Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 為了讓 Beyond Fitness 幫助您達成目標，此問券可以讓我們初步了解您的需求，&lt;br class=&quot;hidden-md-down&quot; /&gt;教練將會在收到表單後與您聯絡並確認安排體驗時間。.
        /// </summary>
        public static string BookNowFormDesc {
            get {
                return ResourceManager.GetString("BookNowFormDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BEYOND FITNESS 夥伴將於 3 天內與您聯繫，做更深入的狀況了解，以及討論如何解決您提出的問題，讓您更安心參加體驗課程，請您再務必留意未接來電 / 簡訊。.
        /// </summary>
        public static string BookNowFormSendPreDesc {
            get {
                return ResourceManager.GetString("BookNowFormSendPreDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 預約.
        /// </summary>
        public static string BookNowStep1 {
            get {
                return ResourceManager.GetString("BookNowStep1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 線上填表單或電話與我們聯繫.
        /// </summary>
        public static string BookNowStep1Desc {
            get {
                return ResourceManager.GetString("BookNowStep1Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 諮詢.
        /// </summary>
        public static string BookNowStep2 {
            get {
                return ResourceManager.GetString("BookNowStep2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 仔細詢問您的健康狀況與喜好.
        /// </summary>
        public static string BookNowStep2Desc {
            get {
                return ResourceManager.GetString("BookNowStep2Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 親身體驗.
        /// </summary>
        public static string BookNowStep3 {
            get {
                return ResourceManager.GetString("BookNowStep3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 針對您的狀況提供與規劃適合的訓練.
        /// </summary>
        public static string BookNowStep3Desc {
            get {
                return ResourceManager.GetString("BookNowStep3Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 量身定做訓練方案.
        /// </summary>
        public static string BookNowStep4 {
            get {
                return ResourceManager.GetString("BookNowStep4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 精心打造的個人化訓練內容.
        /// </summary>
        public static string BookNowStep4Desc {
            get {
                return ResourceManager.GetString("BookNowStep4Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 營養諮詢師.
        /// </summary>
        public static string Dietitian {
            get {
                return ResourceManager.GetString("Dietitian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 您可以透過以下方式聯繫我們完成您的首次體驗課程.
        /// </summary>
        public static string FAQAnsDesc1 {
            get {
                return ResourceManager.GetString("FAQAnsDesc1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 課程推薦.
        /// </summary>
        public static string FAQAnsDesc1_1 {
            get {
                return ResourceManager.GetString("FAQAnsDesc1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 體驗課程內容如下：.
        /// </summary>
        public static string FAQAnsDesc1_2 {
            get {
                return ResourceManager.GetString("FAQAnsDesc1_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 您將會了解您的身體狀況諮詢服務。.
        /// </summary>
        public static string FAQAnsDesc1_2_1 {
            get {
                return ResourceManager.GetString("FAQAnsDesc1_2_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 教練將會細心的了解您的運動狀況與生活型態。.
        /// </summary>
        public static string FAQAnsDesc1_2_2 {
            get {
                return ResourceManager.GetString("FAQAnsDesc1_2_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 遠端課程，專業教練將提前與您視訊確認軟硬體及通訊設備。.
        /// </summary>
        public static string FAQAnsDesc1_2_3 {
            get {
                return ResourceManager.GetString("FAQAnsDesc1_2_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 專業教練將給您期許的運動目標以及運動效果，讓您體驗愉快且健康的課程。.
        /// </summary>
        public static string FAQAnsDesc1_2_4 {
            get {
                return ResourceManager.GetString("FAQAnsDesc1_2_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 教練將與您一同討論專屬於您的客製化訓練。.
        /// </summary>
        public static string FAQAnsDesc1_2_5 {
            get {
                return ResourceManager.GetString("FAQAnsDesc1_2_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 如何收費呢？.
        /// </summary>
        public static string FAQAnsDesc2_1_1 {
            get {
                return ResourceManager.GetString("FAQAnsDesc2_1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 我們的主要服務包含：私人運動訓練（實體，遠端），營養諮詢與規劃，運動傷害防護與運動按摩與伸展.
        /// </summary>
        public static string FAQAnsDesc2_1_2 {
            get {
                return ResourceManager.GetString("FAQAnsDesc2_1_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 實體一對一專業客製的訓練費用以堂數做收費計算，規劃訓練價格會依照您的目標、規劃時間長短及堂數而有所不同 ，價格約落在 TWD$1700- TWD$1900不等。.
        /// </summary>
        public static string FAQAnsDesc2_1_3 {
            get {
                return ResourceManager.GetString("FAQAnsDesc2_1_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 遠端課程訓練費用，營養諮詢規劃，運動傷害防護與運動按摩伸展等服務則依您的實際需求與運動狀況作為相關調整，協助您達到最大的成功。.
        /// </summary>
        public static string FAQAnsDesc2_1_4 {
            get {
                return ResourceManager.GetString("FAQAnsDesc2_1_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 有月費、入會費及手續費嗎？.
        /// </summary>
        public static string FAQAnsDesc2_2_1 {
            get {
                return ResourceManager.GetString("FAQAnsDesc2_2_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beyond Fitness 專注於1對1客製化專業訓練，您無須再繳交任何月費、入會費及手續費。.
        /// </summary>
        public static string FAQAnsDesc2_2_2 {
            get {
                return ResourceManager.GetString("FAQAnsDesc2_2_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 營養服務對於重視自我健康管理者、減重需求者、提升免疫力、三高慢性病族群及重量訓練想提升肌肉量者等，Beyond 的營養課程皆能為您提供良好及完善的成效與服務。.
        /// </summary>
        public static string FAQAnsDesc3_1 {
            get {
                return ResourceManager.GetString("FAQAnsDesc3_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 運動防護則是確認您全身關節與肌肉狀況不可或缺的最大助力，若您有運動傷害，關節與肌肉相關問題，一位運動防護教練是能協助您回歸正常水準最重要的人員。.
        /// </summary>
        public static string FAQAnsDesc3_2 {
            get {
                return ResourceManager.GetString("FAQAnsDesc3_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 運動按摩與伸展對於長期肩頸，下背，或久坐等容易痠痛或狀況的族群，絕對能確實幫助您解決壓力，我們的恢復團隊肯定能讓您展開最健康與舒適的笑容。.
        /// </summary>
        public static string FAQAnsDesc3_3 {
            get {
                return ResourceManager.GetString("FAQAnsDesc3_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beyond Fitness的教練團隊為業界首屈一指的專業團隊， 所有相關人員皆要求國際教練認證資格（國際證照且必須在有效期限內），內部專業團隊學術科考核（每季、半年、一年），以真誠認真的心搭配科學化訓練為根本、系統化紀錄、分析，讓每一位來運動的客戶感受最貼心且值得信任的服務Beyond Fitness 的教練團隊為業界首屈一指的專業教練團隊， 不論是私人訓練、營養規劃、運動恢復與傷害防護，所有相關人員皆俱備國際相關教練及專業認證資格（國際證照且必須在有效期限內），內部專業團隊學術科考核（季考核、半年訓、年訓），並以真誠認真的企業文化搭配科學化訓練，並以雲端系統化紀錄地分析與紀錄輔助，讓每位來運動的客戶感受最貼心且最值得信任的服務。.
        /// </summary>
        public static string FAQAnsDesc4_1 {
            get {
                return ResourceManager.GetString("FAQAnsDesc4_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 優良的一對一私人教練是針對客戶的目標、營養狀況，肌肉關節品質，生活作息並依據當日身體狀況做出客製化的課程安排，同時給予最好的訓練效果，藉此去幫助您達成改變並確實地陪伴您邁向目標。.
        /// </summary>
        public static string FAQAnsDesc5_1 {
            get {
                return ResourceManager.GetString("FAQAnsDesc5_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 最重要地是協助您規劃您生活中其餘非運動時間需要注意的事項，例如營養攝取、筋膜放鬆與傷害防護等，教練能針對客戶的目標去做訓練，並依照每位客戶的獨特性以及差異化給予最為合適有效果的運動哦！.
        /// </summary>
        public static string FAQAnsDesc5_2 {
            get {
                return ResourceManager.GetString("FAQAnsDesc5_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 可以的，我們只提供 BeyondFitness 的客戶登記使用喔，經由規劃專業自主訓練P.I Session，並且進行人數的管控以維持場地以提供客戶最好的運動品質。.
        /// </summary>
        public static string FAQAnsDesc6_1 {
            get {
                return ResourceManager.GetString("FAQAnsDesc6_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 您可以透過以下交通資訊抵達Beyond.
        /// </summary>
        public static string FAQAnsDesc7_1 {
            get {
                return ResourceManager.GetString("FAQAnsDesc7_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 開車/徒步.
        /// </summary>
        public static string FAQAnsDesc7_2 {
            get {
                return ResourceManager.GetString("FAQAnsDesc7_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 捷運.
        /// </summary>
        public static string FAQAnsDesc7_3 {
            get {
                return ResourceManager.GetString("FAQAnsDesc7_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 常見問題.
        /// </summary>
        public static string FAQBannerSlogn {
            get {
                return ResourceManager.GetString("FAQBannerSlogn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 極限，就是征途.
        /// </summary>
        public static string FAQBannerSlognDesc {
            get {
                return ResourceManager.GetString("FAQBannerSlognDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 首次體驗如何預約？.
        /// </summary>
        public static string FAQQestion1 {
            get {
                return ResourceManager.GetString("FAQQestion1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 服務與費用問題？.
        /// </summary>
        public static string FAQQestion2 {
            get {
                return ResourceManager.GetString("FAQQestion2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 營養服務，運動防護與運動按摩適合誰呢(我嗎)？.
        /// </summary>
        public static string FAQQestion3 {
            get {
                return ResourceManager.GetString("FAQQestion3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BEYOND的團隊為何與眾不同？.
        /// </summary>
        public static string FAQQestion4 {
            get {
                return ResourceManager.GetString("FAQQestion4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 一對一私人教練的優點？.
        /// </summary>
        public static string FAQQestion5 {
            get {
                return ResourceManager.GetString("FAQQestion5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 除了教練課之外，平時也可以去健身房運動嗎？.
        /// </summary>
        public static string FAQQestion6 {
            get {
                return ResourceManager.GetString("FAQQestion6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 如何去BEYOND？.
        /// </summary>
        public static string FAQQestion7 {
            get {
                return ResourceManager.GetString("FAQQestion7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 查看目前 Beyond 的職缺.
        /// </summary>
        public static string FindJobs {
            get {
                return ResourceManager.GetString("FindJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 門市一覽.
        /// </summary>
        public static string FindUsBannerSlogn {
            get {
                return ResourceManager.GetString("FindUsBannerSlogn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 現在，可以選擇離你最近的門市.
        /// </summary>
        public static string FindUsBannerSlognDesc {
            get {
                return ResourceManager.GetString("FindUsBannerSlognDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OPENING 關於職缺.
        /// </summary>
        public static string JobOpening {
            get {
                return ResourceManager.GetString("JobOpening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 我們一起.
        /// </summary>
        public static string JoinUsActiviySlogon {
            get {
                return ResourceManager.GetString("JoinUsActiviySlogon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 人生就是不斷超越自己，挑戰極限.
        /// </summary>
        public static string JoinUsActiviySlogonDesc {
            get {
                return ResourceManager.GetString("JoinUsActiviySlogonDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 加入我們，盡展自我.
        /// </summary>
        public static string JoinUsBannerSlogn {
            get {
                return ResourceManager.GetString("JoinUsBannerSlogn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 加入我們的團隊，激盪彼此的火花.
        /// </summary>
        public static string JoinUsBannerSlognDesc {
            get {
                return ResourceManager.GetString("JoinUsBannerSlognDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beyond Fitness 創立於 2014 年，致力於發展專業一對一私人教練。Beyond Fitness從南京小巨蛋發跡，成立以來陸續拓展了信義安和、忠孝、東門等分店，在這些的背後，是一群想用行動與專業實踐理想的夥伴，與背後願意相信 我們的客戶們。我們相信，教育應該是個別化的，訓練也應該是，我們針對個人化的需求去客製最符合「人」的訓練模式，進而引領客戶走向更美好的生活為目標。.
        /// </summary>
        public static string JoinUsCoachDesc {
            get {
                return ResourceManager.GetString("JoinUsCoachDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 我們最喜歡挑戰&lt;br class=&quot;hidden-sm-up&quot; /&gt;&lt;span class=&quot;mark-text-underline&quot;  padding-width=&quot;0.1&quot; bottom-width=&quot;0.1&quot;&gt;不可能&lt;/span&gt;.
        /// </summary>
        public static string JoinUsCoachSlogon {
            get {
                return ResourceManager.GetString("JoinUsCoachSlogon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beyond Fitness 的營養諮詢師能夠為您提供全面的營養諮詢和飲食指導。我們的營養諮詢師擁有豐富的專業知識和經驗，能夠為您量身打造適合您的營養方案，幫助您達成健身和健康目標。不僅能夠為您提供飲食建議和食譜推薦，還能夠協助您檢測營養缺乏或代謝問題，並根據您的身體狀況進行調整和優化營養方案。無論是想要增加肌肉量，還是減少體重，Beyond Fitness 的營養諮詢師都能夠為您提供最專業的建議和支持，讓您在健身和健康的道路上更加順利。.
        /// </summary>
        public static string JoinUsDietitianDesc {
            get {
                return ResourceManager.GetString("JoinUsDietitianDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 客製化營養目標，&lt;br class=&quot;hidden-lg-up&quot; /&gt;助您&lt;span class=&quot;gradient-text-color&quot;&gt;達成目標&lt;/span&gt;.
        /// </summary>
        public static string JoinUsDietitianSlogon {
            get {
                return ResourceManager.GetString("JoinUsDietitianSlogon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 找到適合你的團隊&lt;BR /&gt;自己的精彩故事由&amp;nbsp;BEYOND&amp;nbsp;開始.
        /// </summary>
        public static string JoinUsJobSlogon {
            get {
                return ResourceManager.GetString("JoinUsJobSlogon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beyond Fitness 除了專注於設計客製化的運動計劃和提供專業指導，我們更為您提供綜合性的運動恢復方案。我們的恢復教練具有豐富的專業知識和經驗，能夠協助您在運動後瞬間修復體力，預防受傷，並制定出恰當的運動計劃，確保您的身體達到最佳狀態。不論是想要塑造健美體態，還是為了改善健康狀況，我們都能夠為您提供最專業的健身服務和最全面的恢復指導。.
        /// </summary>
        public static string JoinUsTherapistDesc {
            get {
                return ResourceManager.GetString("JoinUsTherapistDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 提供&lt;span class=&quot;mark-text-underline&quot;  padding-width=&quot;0&quot; bottom-width=&quot;0.1&quot;&gt;個人化&lt;/span&gt;恢復方案的健身專家.
        /// </summary>
        public static string JoinUsTherapistSlogon {
            get {
                return ResourceManager.GetString("JoinUsTherapistSlogon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 私人教練.
        /// </summary>
        public static string PrivateCoach {
            get {
                return ResourceManager.GetString("PrivateCoach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 專一服務，四種體貼.
        /// </summary>
        public static string ServiceBannerSlogn {
            get {
                return ResourceManager.GetString("ServiceBannerSlogn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 獨一無二的服務體驗Exclusive Service.
        /// </summary>
        public static string ServiceBannerSlognDesc {
            get {
                return ResourceManager.GetString("ServiceBannerSlognDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 運動按摩師.
        /// </summary>
        public static string SportTherapist {
            get {
                return ResourceManager.GetString("SportTherapist", resourceCulture);
            }
        }
    }
}
